baseURL = "https://agilebuckle.github.io/glim/"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "AgileBuckle"
    phrases = ["Agile", "Buckle", "Fast", "Snap"]
    links = [
    {name = "Github Profile", url = "https://github.com/AgileBuckle"},    
    {name = "Email", url = "mailto:contact@agilebuckle.com"},    
    ] 
    background = "bg.mp4"
